// <auto-generated />
using System;
using Gerenciamento_Financeiro.infrastructure.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerenciamento_Financeiro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gerenciamento_Financeiro.core.entities.transacao", b =>
                {
                    b.Property<int>("transacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transacaoId"));

                    b.Property<DateOnly>("dataOperacao")
                        .HasColumnType("date");

                    b.Property<int>("tipoOperacao")
                        .HasColumnType("int");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorPosOperacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("transacaoId");

                    b.ToTable("transacao");
                });
#pragma warning restore 612, 618
        }
    }
}
